extends:
  - "@nuxt/eslint-config"
  - "prettier"
overrides:
  - files: "utils/trimAvoidCharacters.js"
    rules:
      no-control-regex: "off"
  - files:
      - "pages/new.vue"
      - "pages/trainer/\\[name\\]/*.vue"
    rules:
      no-irregular-whitespace: "off"
  - files: "composables/*.js"
    # TODO: Auto Imports が考慮されるようになったら取り除いて
    globals:
      ref: true
  - files: "server/utils/*.js"
    # TODO: Auto Imports が考慮されるようになったら取り除いて
    globals:
      useRuntimeConfig: true
  - files: "server/api/*.js"
    # TODO: Auto Imports が考慮されるようになったら取り除いて
    globals:
      fromNodeMiddleware: true
